catalog/urls.py
from django.urls import path

from catalog.views import (index, LiteraryFormatListView, BookListView, AuthorListView,
                           BookDetailView, test_session_view, book_create_view, LiteraryFormatCreateView,
                           LiteraryFormatUpdateView, LiteraryFormatDeleteView, AuthorCreateView, BookCreateView,
                           BookUpdateView)

urlpatterns = [
    path("", index, name="index"),
    # path("literary-formats/", literary_format_list_view, name="literary-format-list"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-format-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-format-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-format-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-format-delete"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/create/", BookCreateView.as_view(), name="book-create"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),
    # path("books/<int:pk>/", book_detail_view, name="book-detail"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
    path("test-session/", test_session_view, name="test-session"),
    # path("books/create/", book_create_view, name="book-create"),
]

app_name = "catalog"

library/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    # path("registration/", include("registration.urls", namespace="registration")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ("username", )

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ("title", )

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format})"

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from catalog.models import Author, Book


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Book
        fields = "__all__"


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("pseudonym", "first_name", "last_name", )


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"})
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.urls import reverse, reverse_lazy

from .forms import BookForm, AuthorCreationForm, BookSearchForm
from .models import Book, Author, LiteraryFormat


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_formats": num_formats,
        "num_visits": num_visits + 1
    }
    return render(request, "catalog/index.html", context=context)


# def literary_format_list_view(request: HttpRequest) -> HttpResponse:
#     literary_format_list = LiteraryFormat.objects.all()
#     context = {
#         "literary_format_list": literary_format_list,
#     }
#     return render(request, "catalog/literary_format_list.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.select_related("format")
    paginate_by = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = BookSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        title = self.request.GET.get("title")
        if title:
            return self.queryset.filter(title__icontains=title)

        return self.queryset



# def book_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
#     book = Book.objects.get(id=pk)
#     context = {
#         "book": book,
#     }
#     return render(request, "catalog/book_detail.html", context=context)


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author


def test_session_view(request):
    return  HttpResponse(
        "<h1>Test session</h1>"
        f"<h4>Session data: {request.session['book']}</h4>"
    )


def book_create_view(request: HttpRequest) -> HttpResponse:
    # if request.method == "GET":
    #     return render(request, "catalog/book_form.html")
    # elif request.method == "POST":
    #     title = request.POST["title"]
    #     price = request.POST["price"]
    #     Book.objects.create(
    #         title=title,
    #         price=price,
    #         format=LiteraryFormat.objects.get(id=1),
    #         authors=Author.objects.get(id=1)
    #     )
    #     return HttpResponseRedirect(reverse("catalog:book-list"))

    if request.method == "GET":
        context = {
            "form": BookForm()
        }
        return render(request, "catalog/book_form.html", context=context)
    elif request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            Book.objects.create(**form.cleaned_data)
            return HttpResponseRedirect(reverse("catalog:book-list"))
        else:
            context = {
                "form": form,
            }
            return render(request, "catalog/book_form.html", context=context)


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_confirm_delete.html"
    success_url = reverse_lazy("catalog:literary-format-list")


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm
    success_url = reverse_lazy("catalog:author-list")


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    fields = "__all__"


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm

templates/accounts/logged_out.html
{% extends "base.html" %}

{% block content %}
  <p>Logged out</p>
  <a href="{% url 'accounts:login' %}">Login</a>
{% endblock %}

templates/base.html
<!DOCTYPE "html">
<html lang="en">
<head>
  {% block title %}
    <title>Library</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}
      {% endblock %}
      {% block pagination %}
        {% include 'includes/pagination.html' %}
      {% endblock %}
    </div>
  </div>

</div>
</body>
</html>

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create author</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Author list<a style="float: right" href="{% url 'catalog:author-create' %}">Create</a></h1>
  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li><a href="#">{{ author.first_name }} {{ author.last_name }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }} <a href="{% url 'catalog:book-update' pk=book.id %}">Edit</a></h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Format: </strong>{{ book.format }}</p>
  <div class="ml-3">
   <h3>Authors:</h3>
  {% for author in book.authors.all %}
    <hr>
    <p class="text-muted">{{ author.id }}</p>
    <p>{{ author.first_name }} {{ author.last_name }}</p>
    {% if author.pseudonym %}
      {{ author.pseudonym }}
    {% endif %}
    {% empty %}
    <p>No authors!</p>
  {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} book</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Book list <a href="{% url 'catalog:book-create' %}">Create</a></h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="submit" class="btn btn-secondary">
  </form>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.price }}, {{ book.format }})</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
  <title>Home page</title>
{% endblock %}
{% block content %}
  <h1>Library home</h1>
  <p>Welcome to the library</p>
  <ul>
    <li>Amount books: {{ num_books }}</li>
    <li>Amount authors: {{ num_authors }}</li>
    <li>Amount formats: {{ num_formats }}</li>
  </ul>
  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}
  </p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete literary format</h1>
  <p>Are you sure you want to delete the literary format: {{ literaryformat }}?</p>
  <p><i>All books with this literary format will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}
  

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} literary format</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Literary format list <a style="float: right" href="{% url 'catalog:literary-format-create' %}">Create</a></h1>
  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for literary_format in literary_format_list %}
        <tr>
        <td>{{ literary_format.id }}</td>
        <td>{{ literary_format.name }}</td>
        <td><a href="{% url 'catalog:literary-format-update' pk=literary_format.id %}">UPDATE</a></td>
        <td><a href="{% url 'catalog:literary-format-delete' pk=literary_format.id %}">DELETE</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats in library</p>
  {% endif %}
{% endblock %}

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"><-</a></li>
    {% endif %}
    <li class="page-item active"><span
        class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">-></a></li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li>
      User: {{ user.username }}
    </li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
{#    <form method="post" action="{% url 'logout' %}">#}
{#      {% csrf_token %}#}
{#      <button type="submit" value="logout">Logout</button>#}
{#    </form>#}
  {% else %}
    <li>
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}
  <br>
  <li>
    <a href="{% url 'catalog:index' %}">Home page</a>
  </li>
  <li>
    <a href="{% url 'catalog:author-list' %}">All authors</a>
  </li>
  <li>
    <a href="{% url 'catalog:book-list' %}">All books</a>
  </li>
  <li>
    <a href="{% url 'catalog:literary-format-list' %}">All literary formats</a>
  </li>
</ul>